user_setting:
  name_length_max: 50
  email_length_max: 255
  password_length_min: 6
  gravata_profile_size: 80
  gravata_index_size: 50
  pw_expired_time: 2

micropost:
  picture_size: 5
  picture_resize: 400
  content_max: 140
  pagination: 10